def construir_saludos_bienvenida(code: str, total: int = 105, offset: int = 0) -> list[str]:
    bloques = {
        "es": {
            "titulos": [
                "Saludos", "Bendiciones", "Paz y gracia", "Bienvenido", "Esperanza",
                "Ánimo", "Gozo", "Fortaleza", "Confianza", "Descanso",
                "Luz", "Consuelo", "Fe", "Misericordia",
            ],
            "deseos": [
                "Que el Señor te sostenga con Su poder y renueve tu ánimo.",
                "Que Dios ilumine tu camino y fortalezca tu corazón en este día.",
                "Que el Señor te cubra con Su amor y te conceda nuevas fuerzas.",
                "Que el Señor te abrace con Su misericordia y te regale descanso.",
                "Que Dios llene tu vida de paz, dirección y esperanza.",
                "Que el Señor te guíe con sabiduría y afirme tus pasos.",
                "Que Cristo sostenga tu corazón y te haga perseverar.",
                "Que el Señor te conceda serenidad en medio de cualquier prueba.",
                "Que Dios te recuerde hoy que no caminas solo.",
                "Que Su presencia te dé reposo, claridad y nueva alegría.",
                "Que el amor del Señor te rodee y te fortalezca por dentro.",
                "Que Dios te levante con gracia y te haga mirar hacia arriba.",
                "Que el Señor avive tu fe y te conceda firmeza.",
                "Que la bondad de Dios acompañe cada paso de tu jornada.",
            ],
            "versiculos": [
                "\"Todo lo puedo en Aquel que me fortalece.\" Filipenses 4:13",
                "\"El Señor es mi pastor; nada me faltará.\" Salmo 23:1",
                "\"Mi paz os dejo, mi paz os doy.\" Juan 14:27",
                "\"Venid a mí todos los que estáis trabajados y cargados.\" Mateo 11:28",
                "\"Jehová es mi luz y mi salvación; ¿de quién temeré?\" Salmo 27:1",
                "\"Echa sobre Jehová tu carga, y Él te sustentará.\" Salmo 55:22",
                "\"Cercano está Jehová a los quebrantados de corazón.\" Salmo 34:18",
                "\"Esforzaos y cobrad ánimo; no temáis.\" Deuteronomio 31:6",
                "\"Los que esperan a Jehová tendrán nuevas fuerzas.\" Isaías 40:31",
                "\"En Dios solamente está acallada mi alma.\" Salmo 62:1",
                "\"La misericordia de Jehová es desde la eternidad.\" Salmo 103:17",
                "\"No te dejaré, ni te desampararé.\" Hebreos 13:5",
            ],
        },
        "ca": {
            "titulos": [
                "Benvingut", "Benediccions", "Pau i gràcia", "Esperança", "Consol",
                "Ànims", "Goig", "Fortalesa", "Confiança", "Repòs",
                "Llum", "Misericòrdia", "Fe", "Serenor",
            ],
            "deseos": [
                "Que el Senyor et sostingui amb el seu poder i renovi el teu ànim.",
                "Que Déu il·lumini el teu camí i enforteixi el teu cor avui.",
                "Que el Senyor et cobreixi amb el seu amor i et doni noves forces.",
                "Que Déu abraci la teva vida i sostingui el teu cor.",
                "Que el Senyor et doni pau, direcció i esperança.",
                "Que Déu guiï els teus passos amb saviesa i fermesa.",
                "Que Crist mantingui viu el teu cor i la teva fe.",
                "Que el Senyor et concedeixi calma enmig de qualsevol prova.",
                "Que Déu et recordi avui que no camines sol.",
                "Que la seva presència et porti repòs i nova alegria.",
                "Que l'amor del Senyor t'envolti i t'enforteixi per dins.",
                "Que Déu t'aixequi amb gràcia i et faci mirar amunt.",
                "Que el Senyor avivi la teva fe i et doni estabilitat.",
                "Que la bondat de Déu acompanyi cada pas del teu dia.",
            ],
            "versiculos": [
                "\"Tot ho puc en aquell que em dona força.\" Filipencs 4:13",
                "\"El Senyor és el meu pastor; no em manca res.\" Salm 23:1",
                "\"Us deixo la pau, us dono la meva pau.\" Joan 14:27",
                "\"Veniu a mi tots els qui esteu cansats i afeixugats.\" Mateu 11:28",
                "\"El Senyor és la meva llum i la meva salvació.\" Salm 27:1",
                "\"Posa la teva càrrega en el Senyor, i ell et sostindrà.\" Salm 55:22",
                "\"El Senyor és a prop dels cors trencats.\" Salm 34:18",
                "\"Sigueu valents i ferms; no tingueu por.\" Deuteronomi 31:6",
                "\"Els qui esperen en el Senyor renovaran les seves forces.\" Isaïes 40:31",
                "\"Només en Déu reposa la meva ànima.\" Salm 62:1",
                "\"La misericòrdia del Senyor és des de sempre i per sempre.\" Salm 103:17",
                "\"No et deixaré ni t'abandonaré.\" Hebreus 13:5",
            ],
        },
        "fr": {
            "titulos": [
                "Bienvenue", "Bénédictions", "Paix et grâce", "Espérance", "Repose-toi",
                "Courage", "Joie", "Force", "Confiance", "Repos",
                "Lumière", "Consolation", "Foi", "Miséricorde",
            ],
            "deseos": [
                "Que le Seigneur te soutienne par sa puissance et renouvelle ton courage.",
                "Que Dieu éclaire ton chemin et fortifie ton cœur aujourd'hui.",
                "Que le Seigneur te couvre de son amour et t'accorde de nouvelles forces.",
                "Que Dieu embrasse ta vie avec sa miséricorde et t'accorde du repos.",
                "Que le Seigneur remplisse ton cœur de paix et d'espérance.",
                "Que Dieu guide tes pas avec sagesse et douceur.",
                "Que le Christ soutienne ton intérieur et fortifie ta foi.",
                "Que le Seigneur te donne du calme au milieu de l'épreuve.",
                "Que Dieu te rappelle aujourd'hui que tu n'es pas seul.",
                "Que sa présence t'apporte du repos et une joie nouvelle.",
                "Que l'amour du Seigneur t'entoure et te rende ferme.",
                "Que Dieu te relève avec grâce et te fasse regarder en haut.",
                "Que le Seigneur ravive ta foi et affermisse ton cœur.",
                "Que la bonté de Dieu accompagne chacun de tes pas.",
            ],
            "versiculos": [
                "\"Je puis tout par celui qui me fortifie.\" Philippiens 4:13",
                "\"L'Éternel est mon berger : je ne manquerai de rien.\" Psaume 23:1",
                "\"Je vous laisse la paix, je vous donne ma paix.\" Jean 14:27",
                "\"Venez à moi, vous tous qui êtes fatigués et chargés.\" Matthieu 11:28",
                "\"L'Éternel est ma lumière et mon salut.\" Psaume 27:1",
                "\"Remets ton sort à l'Éternel, et il te soutiendra.\" Psaume 55:22",
                "\"L'Éternel est près de ceux qui ont le cœur brisé.\" Psaume 34:18",
                "\"Fortifiez-vous et ayez du courage; ne craignez point.\" Deutéronome 31:6",
                "\"Ceux qui se confient en l'Éternel renouvellent leur force.\" Ésaïe 40:31",
                "\"Oui, c'est en Dieu que mon âme se repose.\" Psaume 62:1",
                "\"La bonté de l'Éternel dure à toujours.\" Psaume 103:17",
                "\"Je ne te délaisserai point, et je ne t'abandonnerai point.\" Hébreux 13:5",
            ],
        },
        "en": {
            "titulos": [
                "Welcome", "Blessings", "Peace and grace", "Hope", "Rest",
                "Courage", "Joy", "Strength", "Confidence", "Peace",
                "Light", "Comfort", "Faith", "Mercy",
            ],
            "deseos": [
                "May the Lord uphold you with His power and renew your spirit today.",
                "May God light your path and strengthen your heart this day.",
                "May the Lord cover you with His love and give you fresh strength.",
                "May God hold your life with mercy and give you rest.",
                "May the Lord fill your heart with peace, direction, and hope.",
                "May God guide your steps with wisdom and kindness.",
                "May Christ sustain your heart and keep your faith alive.",
                "May the Lord grant you calm in the middle of every trial.",
                "May God remind you today that you do not walk alone.",
                "May His presence bring you rest and new joy.",
                "May the love of the Lord surround you and make you strong within.",
                "May God lift you up with grace and turn your eyes upward.",
                "May the Lord revive your faith and steady your soul.",
                "May the goodness of God accompany every step of your day.",
            ],
            "versiculos": [
                "\"I can do all things through Christ who strengthens me.\" Philippians 4:13",
                "\"The Lord is my shepherd; I shall not want.\" Psalm 23:1",
                "\"Peace I leave with you, My peace I give to you.\" John 14:27",
                "\"Come to Me, all you who labor and are heavy laden.\" Matthew 11:28",
                "\"The Lord is my light and my salvation; whom shall I fear?\" Psalm 27:1",
                "\"Cast your burden on the Lord, and He shall sustain you.\" Psalm 55:22",
                "\"The Lord is near to the brokenhearted.\" Psalm 34:18",
                "\"Be strong and of a good courage; do not fear.\" Deuteronomy 31:6",
                "\"Those who wait on the Lord shall renew their strength.\" Isaiah 40:31",
                "\"Truly my soul silently waits for God.\" Psalm 62:1",
                "\"The mercy of the Lord is from everlasting to everlasting.\" Psalm 103:17",
                "\"I will never leave you nor forsake you.\" Hebrews 13:5",
            ],
        },
    }
    bloque = bloques.get(code, bloques["es"])
    titulos = bloque["titulos"]
    deseos = bloque["deseos"]
    versiculos = bloque["versiculos"]
    combinaciones = [
        f"{titulo}\n{deseo}\n{versiculo}"
        for deseo in deseos
        for versiculo in versiculos
        for titulo in titulos
    ]
    if not combinaciones:
        return []

    paso = 23
    inicio = sum(ord(caracter) for caracter in code) % len(combinaciones)
    return [
        combinaciones[(inicio + indice * paso) % len(combinaciones)]
        for indice in range(offset, offset + total)
    ]


def construir_saludo_bienvenida(code: str, indice: int = 0) -> str:
    saludos = construir_saludos_bienvenida(code, total=1, offset=indice)
    return saludos[0] if saludos else ""


LANGUAGES = {
    "es": {
        "code": "es",
        "name": "Español",
        "native_name": "Español",
        "flag": "spain",
        "prompt_language": "español de España",
        "bible_versions": [
            ("Ninguna", "Ninguna"),
            ("RV1960", "Reina-Valera 1960"),
            ("RVR95", "Reina-Valera Revisada 1995"),
            ("NVI", "Nueva Versión Internacional"),
            ("NTV", "Nueva Traducción Viviente"),
            ("LBLA", "La Biblia de las Américas"),
            ("DHH", "Dios Habla Hoy"),
            ("BLP", "Biblia Lenguaje Actual"),
            ("TLA", "Traducción en Lenguaje Actual"),
            ("JBS", "Jubileo 2000"),
            ("PDT", "Palabra de Dios para Todos"),
        ],
        "selector": {
            "title": "",
            "subtitle": "La Palabra, en tu idioma.",
        },
        "welcome": {
            "title": "Biblia IA",
            "subtitle": (
                "Esta aplicación es gratuita. Si deseas agradecérmelo, puedes seguirme en TikTok."
            ),
            "update_notice": "Recuerda ir actualizando la aplicación para recibir novedades, mejoras y posibles correcciones.",
            "continue": "CONTINUAR",
            "follow": "SEGUIR EN TIKTOK",
            "back": "CAMBIAR IDIOMA",
            "snackbar_open_error": "No se pudo abrir TikTok: {error}",
            "greetings": [
                "Saludos\nQue el Señor te sostenga con Su poder y renueve tu ánimo.\n\"Todo lo puedo en Aquel que me fortalece.\" Filipenses 4:13",
                "Bendiciones\nQue Dios ilumine tu camino y fortalezca tu corazón en este día.\n\"El Señor es mi pastor; nada me faltará.\" Salmo 23:1",
                "Paz y gracia\nQue el Señor te cubra con Su amor y te conceda nuevas fuerzas.\n\"Mi paz os dejo, mi paz os doy.\" Juan 14:27",
                "Bienvenido\nQue el Señor te abrace con Su misericordia y te regale descanso.\n\"Venid a mí los cansados y cargados.\" Mateo 11:28",
                "Esperanza\nQue el Señor ilumine tus días y te conceda la paz que sobrepasa todo entendimiento.\n\"Jehová es mi luz y mi salvación; ¿de quién temeré?\" Salmo 27:1",
            ],
        },
        "ui": {
            "title": "Biblia IA",
            "version": "VERSION",
            "none": "Ninguna",
            "book_order": "ORDEN DE LIBROS",
            "biblical_order": "Orden bíblico",
            "alphabetical_order": "Ordenados alfabéticamente",
            "book": "LIBRO",
            "chapter": "CAPÍTULO",
            "start": "INICIO",
            "end": "FINAL",
            "study_type": "TIPO DE ESTUDIO",
            "words": "CANTIDAD DE PALABRAS",
            "no_selection": "Ninguno",
            "random": "ALEATORIO",
            "generate": "GENERAR RESULTADO",
            "generating_pdf": "GENERANDO PDF...",
            "ask": "PREGUNTA",
            "copy_result": "COPIAR RESULTADO",
            "generate_pdf": "GENERAR PDF",
            "clear_result": "ANTES DE SALIR ELIMINAR RESULTADO",
            "clear_filters": "LIMPIAR FILTROS",
            "search_filters": "FILTROS DE BUSQUEDA",
            "result": "RESULTADO",
            "back_to_filters": "VOLVER A FILTROS",
            "back_step": "VOLVER ATRAS",
            "back_to_start": "VOLVER A SELECCION",
            "passage": "PASAJE BÍBLICO",
            "question_placeholder": "pregunta cualquier cosa a la ia",
            "entry_title": "Como quieres empezar?",
            "entry_subtitle": "Elige si quieres buscar un pasaje biblico o hacer un estudio por tema, personaje, lugar y otros filtros.",
            "entry_bible": "BIBLIA",
            "entry_bible_help": "Ir al recuadro de pasaje biblico",
            "entry_study": "ESTUDIO BIBLICO",
            "entry_study_help": "TEMAS, PERSONAJES, PUEBLOS, ETC",
            "empty_result": "Aquí aparecerá el resultado generado.",
            "status_ready": "Estado: listo para generar o preguntar",
            "status_generating": "Estado: generando estudio...",
            "status_ready_study": "Estado: estudio listo",
            "status_asking": "Estado: consultando a la IA...",
            "status_answer_ready": "Estado: respuesta lista",
            "status_error": "Estado: hubo un problema al consultar la IA",
            "status_repeat": "Estado: repitiendo última consulta...",
            "status_repeat_ready": "Estado: consulta repetida y lista",
            "msg_select_something": "Selecciona un libro, un filtro especial o una sugerencia de tema",
            "msg_select_study_type": "Selecciona un tipo de estudio",
            "msg_write_question": "Escribe una pregunta primero",
            "msg_no_content": "No hay contenido generado aún",
            "msg_copied": "Resultado copiado al portapapeles",
            "msg_pdf_created": "PDF generado en: {path}",
            "msg_pdf_error": "No se pudo generar el PDF: {error}",
            "msg_path_copied": "Ruta del PDF copiada al portapapeles",
            "pdf_saved_title": "PDF generado",
            "pdf_saved_help": "Si no se abre automáticamente, aquí tienes la ruta exacta:",
            "copy_path": "COPIAR RUTA",
            "open_pdf": "ABRIR PDF",
            "open_folder": "ABRIR CARPETA",
            "close": "CERRAR",
            "msg_no_previous": "Todavía no hay una consulta previa para repetir",
            "msg_no_random_options": "No hay opciones disponibles para seleccionar al azar",
            "msg_random_selection": "Selección aleatoria: {label}",
            "male_character": "Personaje masculino",
            "female_character": "Personaje femenino",
            "groups": "Grupos y colectivos bíblicos",
            "people_nation": "Pueblo/Nación",
            "place": "Lugar geográfico",
            "religions": "Religiones del mundo",
            "suggested_topic": "Tema sugerido",
            "study_info": "Estudio informativo",
            "verse_study": "Estudio versículos",
            "biblical_reflection": "Reflexión bíblica",
            "practical_application": "Aplicación práctica",
            "sermon_outline": "Bosquejo para predicar",
            "brief_devotional": "Devocional breve",
            "only_verses": "Solo versículos",
        },
    },
    "ca": {
        "code": "ca",
        "name": "Catalán",
        "native_name": "Català",
        "flag": "catalonia",
        "prompt_language": "català",
        "bible_versions": [
            ("Ninguna", "Cap"),
            ("BCI", "Bíblia Catalana Interconfessional"),
            ("BJ", "Bíblia de Jerusalem"),
            ("EV", "Els Evangelis"),
        ],
        "selector": {
            "title": "Tria el teu idioma",
            "subtitle": "Selecciona l'idioma amb què vols utilitzar l'aplicació.",
        },
        "welcome": {
            "title": "Biblia IA",
            "subtitle": (
                "Aquesta aplicació és gratuïta. Si vols agrair-m'ho, em pots seguir a TikTok."
            ),
            "update_notice": "Recorda anar actualitzant l'aplicació per rebre novetats, millores i possibles correccions.",
            "continue": "CONTINUAR",
            "follow": "SEGUIR A TIKTOK",
            "back": "CANVIAR IDIOMA",
            "snackbar_open_error": "No s'ha pogut obrir TikTok: {error}",
            "greetings": [
                "Benvingut\nQue el Senyor et sostingui amb el seu poder i renovi el teu ànim.\n\"Tot ho puc en aquell que em dona força.\" Filipencs 4:13",
                "Benediccions\nQue Déu il·lumini el teu camí i enforteixi el teu cor avui.\n\"El Senyor és el meu pastor; no em manca res.\" Salm 23:1",
                "Pau i gràcia\nQue el Senyor et cobreixi amb el seu amor i et doni noves forces.\n\"Us deixo la pau, us dono la meva pau.\" Joan 14:27",
                "Esperança\nQue el Senyor il·lumini els teus dies i t'ompli de serenor.\n\"El Senyor és la meva llum i la meva salvació.\" Salm 27:1",
                "Consol\nQue Déu abraci la teva vida i sostingui el teu cor.\n\"Veniu a mi tots els qui esteu cansats.\" Mateu 11:28",
            ],
        },
        "ui": {
            "title": "Biblia IA",
            "version": "VERSIO",
            "none": "Cap",
            "book_order": "ORDRE DELS LLIBRES",
            "biblical_order": "Ordre bíblic",
            "alphabetical_order": "Ordre alfabètic",
            "book": "LLIBRE",
            "chapter": "CAPÍTOL",
            "start": "INICI",
            "end": "FINAL",
            "study_type": "TIPUS D'ESTUDI",
            "words": "QUANTITAT DE PARAULES",
            "no_selection": "Cap",
            "random": "ALEATORI",
            "generate": "GENERAR RESULTAT",
            "generating_pdf": "GENERANT PDF...",
            "ask": "PREGUNTA",
            "copy_result": "COPIAR RESULTAT",
            "generate_pdf": "GENERAR PDF",
            "clear_result": "ABANS DE SORTIR ELIMINA EL RESULTAT",
            "clear_filters": "NETEJAR FILTRES",
            "search_filters": "FILTRES DE CERCA",
            "result": "RESULTAT",
            "back_to_filters": "TORNAR ALS FILTRES",
            "back_step": "TORNAR ENRERE",
            "back_to_start": "TORNAR A SELECCIO",
            "passage": "PASSATGE BÍBLIC",
            "question_placeholder": "pregunta el que vulguis a la ia",
            "entry_title": "Com vols comencar?",
            "entry_subtitle": "Tria si vols cercar un passatge biblic o fer un estudi per tema, personatge, lloc i altres filtres.",
            "entry_bible": "BIBLIA",
            "entry_bible_help": "Anar al requadre de passatge biblic",
            "entry_study": "ESTUDI",
            "entry_study_help": "Anar al requadre de tema, personatge, lloc i filtres",
            "empty_result": "Aquí apareixerà el resultat generat.",
            "status_ready": "Estat: a punt per generar o preguntar",
            "status_generating": "Estat: generant estudi...",
            "status_ready_study": "Estat: estudi llest",
            "status_asking": "Estat: consultant la IA...",
            "status_answer_ready": "Estat: resposta llesta",
            "status_error": "Estat: hi ha hagut un problema en consultar la IA",
            "status_repeat": "Estat: repetint l'última consulta...",
            "status_repeat_ready": "Estat: consulta repetida i llesta",
            "msg_select_something": "Selecciona un llibre, un filtre especial o un tema suggerit",
            "msg_select_study_type": "Selecciona un tipus d'estudi",
            "msg_write_question": "Escriu primer una pregunta",
            "msg_no_content": "Encara no hi ha contingut generat",
            "msg_copied": "Resultat copiat al porta-retalls",
            "msg_pdf_created": "PDF generat a: {path}",
            "msg_pdf_error": "No s'ha pogut generar el PDF: {error}",
            "msg_path_copied": "Ruta del PDF copiada al porta-retalls",
            "pdf_saved_title": "PDF generat",
            "pdf_saved_help": "Si no s'obre automàticament, aquí tens la ruta exacta:",
            "copy_path": "COPIAR RUTA",
            "open_pdf": "OBRIR PDF",
            "open_folder": "OBRIR CARPETA",
            "close": "TANCAR",
            "msg_no_previous": "Encara no hi ha una consulta prèvia per repetir",
            "msg_no_random_options": "No hi ha opcions disponibles per triar a l'atzar",
            "msg_random_selection": "Selecció aleatòria: {label}",
            "male_character": "Personatge masculí",
            "female_character": "Personatge femení",
            "groups": "Grups i col·lectius bíblics",
            "people_nation": "Poble/Nació",
            "place": "Lloc geogràfic",
            "religions": "Religions del món",
            "suggested_topic": "Tema suggerit",
            "study_info": "Estudi informatiu",
            "verse_study": "Estudi versicles",
            "biblical_reflection": "Reflexió bíblica",
            "practical_application": "Aplicació pràctica",
            "sermon_outline": "Esquema per predicar",
            "brief_devotional": "Devocional breu",
            "only_verses": "Només versicles",
        },
    },
    "fr": {
        "code": "fr",
        "name": "Francés",
        "native_name": "Français",
        "flag": "france",
        "prompt_language": "français",
        "bible_versions": [
            ("Ninguna", "Aucune"),
            ("LSG", "Louis Segond"),
            ("BDS", "Bible du Semeur"),
            ("NBS", "Nouvelle Bible Segond"),
            ("SG21", "Segond 21"),
        ],
        "selector": {
            "title": "Choisissez votre langue",
            "subtitle": "Sélectionnez la langue dans laquelle vous voulez utiliser l'application.",
        },
        "welcome": {
            "title": "Biblia IA",
            "subtitle": (
                "Cette application est gratuite. Si vous voulez me remercier, vous pouvez me suivre sur TikTok."
            ),
            "update_notice": "Pense à mettre l'application à jour pour recevoir les nouveautés, les améliorations et les éventuelles corrections.",
            "continue": "CONTINUER",
            "follow": "SUIVRE SUR TIKTOK",
            "back": "CHANGER DE LANGUE",
            "snackbar_open_error": "Impossible d'ouvrir TikTok : {error}",
            "greetings": [
                "Bienvenue\nQue le Seigneur te soutienne par sa puissance et renouvelle ton courage.\n\"Je puis tout par celui qui me fortifie.\" Philippiens 4:13",
                "Bénédictions\nQue Dieu éclaire ton chemin et fortifie ton cœur aujourd'hui.\n\"L'Éternel est mon berger : je ne manquerai de rien.\" Psaume 23:1",
                "Paix et grâce\nQue le Seigneur te couvre de son amour et t'accorde de nouvelles forces.\n\"Je vous laisse la paix, je vous donne ma paix.\" Jean 14:27",
                "Espérance\nQue le Seigneur illumine tes jours et te donne une paix profonde.\n\"L'Éternel est ma lumière et mon salut.\" Psaume 27:1",
                "Repose-toi\nQue le Seigneur soulage tes fardeaux et raffermisse ton intérieur.\n\"Venez à moi, vous tous qui êtes fatigués.\" Matthieu 11:28",
            ],
        },
        "ui": {
            "title": "Biblia IA",
            "version": "VERSION",
            "none": "Aucune",
            "book_order": "ORDRE DES LIVRES",
            "biblical_order": "Ordre biblique",
            "alphabetical_order": "Ordre alphabétique",
            "book": "LIVRE",
            "chapter": "CHAPITRE",
            "start": "DEBUT",
            "end": "FIN",
            "study_type": "TYPE D'ETUDE",
            "words": "QUANTITE DE MOTS",
            "no_selection": "Aucun",
            "random": "ALEATOIRE",
            "generate": "GENERER LE RESULTAT",
            "generating_pdf": "GENERERATION DU PDF...",
            "ask": "QUESTION",
            "copy_result": "COPIER LE RESULTAT",
            "generate_pdf": "GENERER LE PDF",
            "clear_result": "SUPPRIMER LE RESULTAT AVANT DE SORTIR",
            "clear_filters": "EFFACER LES FILTRES",
            "search_filters": "FILTRES DE RECHERCHE",
            "result": "RESULTAT",
            "back_to_filters": "RETOUR AUX FILTRES",
            "back_step": "RETOUR",
            "back_to_start": "RETOUR A LA SELECTION",
            "passage": "PASSAGE BIBLIQUE",
            "question_placeholder": "demandez ce que vous voulez a l'ia",
            "entry_title": "Comment veux-tu commencer ?",
            "entry_subtitle": "Choisis si tu veux chercher un passage biblique ou faire une étude par thème, personnage, lieu et autres filtres.",
            "entry_bible": "BIBLE",
            "entry_bible_help": "Aller au cadre du passage biblique",
            "entry_study": "ETUDE",
            "entry_study_help": "Aller au cadre du thème, personnage, lieu et filtres",
            "empty_result": "Le résultat généré apparaîtra ici.",
            "status_ready": "Etat : prêt à générer ou poser une question",
            "status_generating": "Etat : génération de l'étude...",
            "status_ready_study": "Etat : étude prête",
            "status_asking": "Etat : consultation de l'IA...",
            "status_answer_ready": "Etat : réponse prête",
            "status_error": "Etat : un problème est survenu lors de la consultation de l'IA",
            "status_repeat": "Etat : répétition de la dernière consultation...",
            "status_repeat_ready": "Etat : consultation répétée et prête",
            "msg_select_something": "Sélectionnez un livre, un filtre spécial ou un thème suggéré",
            "msg_select_study_type": "Sélectionnez un type d'étude",
            "msg_write_question": "Ecrivez d'abord une question",
            "msg_no_content": "Aucun contenu généré pour le moment",
            "msg_copied": "Résultat copié dans le presse-papiers",
            "msg_pdf_created": "PDF généré dans : {path}",
            "msg_pdf_error": "Impossible de générer le PDF : {error}",
            "msg_path_copied": "Chemin du PDF copié dans le presse-papiers",
            "pdf_saved_title": "PDF généré",
            "pdf_saved_help": "S'il ne s'ouvre pas automatiquement, voici le chemin exact :",
            "copy_path": "COPIER LE CHEMIN",
            "open_pdf": "OUVRIR LE PDF",
            "open_folder": "OUVRIR LE DOSSIER",
            "close": "FERMER",
            "msg_no_previous": "Il n'y a pas encore de consultation précédente à répéter",
            "msg_no_random_options": "Aucune option disponible pour une sélection aléatoire",
            "msg_random_selection": "Sélection aléatoire : {label}",
            "male_character": "Personnage masculin",
            "female_character": "Personnage féminin",
            "groups": "Groupes et collectifs bibliques",
            "people_nation": "Peuple/Nation",
            "place": "Lieu géographique",
            "religions": "Religions du monde",
            "suggested_topic": "Thème suggéré",
            "study_info": "Etude informative",
            "verse_study": "Etude versets",
            "biblical_reflection": "Réflexion biblique",
            "practical_application": "Application pratique",
            "sermon_outline": "Plan de prédication",
            "brief_devotional": "Dévotion brève",
            "only_verses": "Versets seulement",
        },
    },
    "en": {
        "code": "en",
        "name": "Inglés",
        "native_name": "English",
        "flag": "uk",
        "prompt_language": "English",
        "bible_versions": [
            ("Ninguna", "None"),
            ("KJV", "King James Version"),
            ("NIV", "New International Version"),
            ("ESV", "English Standard Version"),
            ("NLT", "New Living Translation"),
        ],
        "selector": {
            "title": "Choose your language",
            "subtitle": "Select the language you want to use in the application.",
        },
        "welcome": {
            "title": "Biblia IA",
            "subtitle": (
                "This application is free. If you would like to thank me, you can follow me on TikTok."
            ),
            "update_notice": "Remember to keep the app updated so you receive new features, improvements, and possible fixes.",
            "continue": "CONTINUE",
            "follow": "FOLLOW ON TIKTOK",
            "back": "CHANGE LANGUAGE",
            "snackbar_open_error": "TikTok could not be opened: {error}",
            "greetings": [
                "Welcome\nMay the Lord sustain you with His power and renew your strength.\n\"I can do all things through Christ who strengthens me.\" Philippians 4:13",
                "Blessings\nMay God light your path and strengthen your heart today.\n\"The Lord is my shepherd; I shall not want.\" Psalm 23:1",
                "Peace and grace\nMay the Lord cover you with His love and grant you fresh strength.\n\"Peace I leave with you; my peace I give unto you.\" John 14:27",
                "Hope\nMay the Lord brighten your days and fill you with deep peace.\n\"The Lord is my light and my salvation; whom shall I fear?\" Psalm 27:1",
                "Rest\nMay the Lord ease every burden you carry and strengthen you within.\n\"Come unto me, all ye that labour and are heavy laden.\" Matthew 11:28",
            ],
        },
        "ui": {
            "title": "Biblia IA",
            "version": "VERSION",
            "none": "None",
            "book_order": "BOOK ORDER",
            "biblical_order": "Biblical order",
            "alphabetical_order": "Alphabetical order",
            "book": "BOOK",
            "chapter": "CHAPTER",
            "start": "START",
            "end": "END",
            "study_type": "STUDY TYPE",
            "words": "WORD COUNT",
            "no_selection": "None",
            "random": "RANDOM",
            "generate": "GENERATE RESULT",
            "generating_pdf": "GENERATING PDF...",
            "ask": "QUESTION",
            "copy_result": "COPY RESULT",
            "generate_pdf": "GENERATE PDF",
            "clear_result": "CLEAR RESULT BEFORE EXITING",
            "clear_filters": "CLEAR FILTERS",
            "search_filters": "SEARCH FILTERS",
            "result": "RESULT",
            "back_to_filters": "BACK TO FILTERS",
            "back_step": "GO BACK",
            "back_to_start": "BACK TO SELECTION",
            "passage": "BIBLE PASSAGE",
            "question_placeholder": "ask the ai anything you want",
            "entry_title": "How do you want to start?",
            "entry_subtitle": "Choose whether you want to search a Bible passage or start a study by topic, character, place, and other filters.",
            "entry_bible": "BIBLE",
            "entry_bible_help": "Go to the Bible passage panel",
            "entry_study": "STUDY",
            "entry_study_help": "Go to the topic, character, place, and filters panel",
            "empty_result": "The generated result will appear here.",
            "status_ready": "Status: ready to generate or ask",
            "status_generating": "Status: generating study...",
            "status_ready_study": "Status: study ready",
            "status_asking": "Status: asking the AI...",
            "status_answer_ready": "Status: answer ready",
            "status_error": "Status: there was a problem while consulting the AI",
            "status_repeat": "Status: repeating the last query...",
            "status_repeat_ready": "Status: repeated query ready",
            "msg_select_something": "Select a book, a special filter, or a suggested topic",
            "msg_select_study_type": "Select a study type",
            "msg_write_question": "Write a question first",
            "msg_no_content": "There is no generated content yet",
            "msg_copied": "Result copied to clipboard",
            "msg_pdf_created": "PDF generated at: {path}",
            "msg_pdf_error": "Could not generate the PDF: {error}",
            "msg_path_copied": "PDF path copied to clipboard",
            "pdf_saved_title": "PDF generated",
            "pdf_saved_help": "If it does not open automatically, here is the exact path:",
            "copy_path": "COPY PATH",
            "open_pdf": "OPEN PDF",
            "open_folder": "OPEN FOLDER",
            "close": "CLOSE",
            "msg_no_previous": "There is no previous query to repeat yet",
            "msg_no_random_options": "There are no options available for random selection",
            "msg_random_selection": "Random selection: {label}",
            "male_character": "Male character",
            "female_character": "Female character",
            "groups": "Biblical groups and collectives",
            "people_nation": "People/Nation",
            "place": "Geographical place",
            "religions": "Religions of the world",
            "suggested_topic": "Suggested topic",
            "study_info": "Informative study",
            "verse_study": "Verse study",
            "biblical_reflection": "Biblical reflection",
            "practical_application": "Practical application",
            "sermon_outline": "Preaching outline",
            "brief_devotional": "Brief devotional",
            "only_verses": "Verses only",
        },
    },
}
for _codigo_bienvenida in ("es", "ca", "fr", "en"):
    LANGUAGES[_codigo_bienvenida]["welcome"]["greetings"] = construir_saludos_bienvenida(_codigo_bienvenida)

LANGUAGES["es"]["ui"].update({
    "version": "VERSIÓN",
    "search_filters": "FILTROS DE BÚSQUEDA",
    "back_step": "VOLVER ATRÁS",
    "back_to_start": "VOLVER A SELECCIÓN",
    "passage": "PASAJE BÍBLICO",
    "entry_title": "¿Cómo quieres empezar?",
    "entry_subtitle": "Elige si quieres buscar un pasaje bíblico o hacer un estudio por tema, personaje, lugar y otros filtros.",
    "entry_bible_help": "Ir al recuadro de pasaje bíblico",
    "entry_study": "ESTUDIO BÍBLICO",
    "empty_result": "Aquí aparecerá el resultado generado.",
    "status_repeat": "Estado: repitiendo última consulta...",
    "msg_no_content": "No hay contenido generado aún",
    "msg_no_previous": "Todavía no hay una consulta previa para repetir",
    "msg_random_selection": "Selección aleatoria: {label}",
    "groups": "Grupos y colectivos bíblicos",
    "people_nation": "Pueblo/Nación",
    "place": "Lugar geográfico",
    "biblical_reflection": "Reflexión bíblica",
    "practical_application": "Aplicación práctica",
    "sermon_outline": "Bosquejo para predicar",
    "only_verses": "Solo versículos",
})

LANGUAGES["ca"].update({
    "name": "Català",
    "native_name": "Català",
    "prompt_language": "català",
})
LANGUAGES["ca"]["ui"].update({
    "version": "VERSIÓ",
    "back_to_start": "TORNAR A SELECCIÓ",
    "passage": "PASSATGE BÍBLIC",
    "entry_title": "Com vols començar?",
    "entry_subtitle": "Tria si vols cercar un passatge bíblic o fer un estudi per tema, personatge, lloc i altres filtres.",
    "entry_bible": "BÍBLIA",
    "entry_bible_help": "Anar al requadre de passatge bíblic",
    "entry_study": "ESTUDI BÍBLIC",
    "question_placeholder": "pregunta el que vulguis a la IA",
    "empty_result": "Aquí apareixerà el resultat generat.",
    "status_repeat": "Estat: repetint l'última consulta...",
    "msg_no_previous": "Encara no hi ha una consulta prèvia per repetir",
    "msg_random_selection": "Selecció aleatòria: {label}",
    "groups": "Grups i col·lectius bíblics",
    "people_nation": "Poble/Nació",
    "place": "Lloc geogràfic",
    "religions": "Religions del món",
    "biblical_reflection": "Reflexió bíblica",
    "practical_application": "Aplicació pràctica",
    "sermon_outline": "Esquema per predicar",
    "only_verses": "Només versicles",
})

LANGUAGES["fr"].update({
    "name": "Français",
    "native_name": "Français",
    "prompt_language": "français",
})
LANGUAGES["fr"]["ui"].update({
    "start": "DÉBUT",
    "study_type": "TYPE D'ÉTUDE",
    "words": "QUANTITÉ DE MOTS",
    "random": "ALÉATOIRE",
    "generate": "GÉNÉRER ET AFFICHER LE RÉSULTAT",
    "copy_result": "COPIER LE RÉSULTAT",
    "result": "RÉSULTAT",
    "back_to_start": "RETOUR À LA SÉLECTION",
    "question_placeholder": "demandez ce que vous voulez à l'IA",
    "entry_title": "Comment veux-tu commencer ?",
    "entry_subtitle": "Choisis si tu veux chercher un passage biblique ou faire une étude par thème, personnage, lieu et autres filtres.",
    "entry_bible_help": "Aller au cadre du passage biblique",
    "entry_study": "ÉTUDE",
    "status_ready": "État : prêt à générer ou poser une question",
    "status_generating": "État : génération de l'étude...",
    "status_ready_study": "État : étude prête",
    "status_asking": "État : consultation de l'IA...",
    "status_answer_ready": "État : réponse prête",
    "status_error": "État : un problème est survenu lors de la consultation de l'IA",
    "status_repeat": "État : répétition de la dernière consultation...",
    "status_repeat_ready": "État : consultation répétée et prête",
    "msg_write_question": "Écrivez d'abord une question",
    "study_info": "Étude informative",
    "sermon_outline": "Plan de prédication",
})

LANGUAGES["en"]["welcome"]["greetings"] = construir_saludos_bienvenida("en")


DEFAULT_LANGUAGE = "es"


LANGUAGE_THEMES = {
    "es": {
        "primary": "#C60B1E",
        "secondary": "#FFC400",
        "accent": "#FFF1B8",
        "field_border": "#FFC400",
        "panel_border": "#C60B1E",
        "text": "#2F1B00",
        "page_bg": "#FFF6E8",
        "panel_bg": "#FFFDF5",
        "field_bg": "#FFF4CC",
        "primary_text": "#FFFFFF",
        "secondary_text": "#2F1B00",
        "border": "#3C2200",
        "muted": "#7A5C36",
    },
    "ca": {
        "primary": "#C8102E",
        "secondary": "#F6D04D",
        "accent": "#FFE9A3",
        "field_border": "#F6D04D",
        "panel_border": "#C8102E",
        "text": "#351600",
        "page_bg": "#FFF7E8",
        "panel_bg": "#FFFDF4",
        "field_bg": "#FFF1C2",
        "primary_text": "#FFFFFF",
        "secondary_text": "#351600",
        "border": "#522100",
        "muted": "#7F5E1A",
    },
    "fr": {
        "primary": "#0055A4",
        "secondary": "#BFD9FF",
        "accent": "#EAF4FF",
        "field_border": "#EF4135",
        "panel_border": "#EF4135",
        "text": "#10233C",
        "page_bg": "#F8FAFF",
        "panel_bg": "#EAF4FF",
        "field_bg": "#DCEBFF",
        "primary_text": "#FFFFFF",
        "secondary_text": "#123156",
        "border": "#132A45",
        "muted": "#5D6F86",
    },
    "en": {
        "primary": "#012169",
        "secondary": "#C7D9FF",
        "accent": "#EEF4FF",
        "field_border": "#C8102E",
        "panel_border": "#C8102E",
        "text": "#0E1D3A",
        "page_bg": "#F7F9FF",
        "panel_bg": "#EEF4FF",
        "field_bg": "#DDE8FF",
        "primary_text": "#FFFFFF",
        "secondary_text": "#12264A",
        "border": "#0B1833",
        "muted": "#5C6988",
    },
}


def get_language_config(code: str | None):
    return LANGUAGES.get(code or DEFAULT_LANGUAGE, LANGUAGES[DEFAULT_LANGUAGE])


def get_ui(code: str | None):
    return get_language_config(code)["ui"]


def get_language_theme(code: str | None):
    language_code = get_language_config(code)["code"]
    return LANGUAGE_THEMES.get(language_code, LANGUAGE_THEMES[DEFAULT_LANGUAGE])




